apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: Rick O <rosowski@gmail.com>
    commit.image.appsody.dev/committer: GitHub <noreply@github.com>
    commit.image.appsody.dev/contextDir: C:\dev\refarch\appsody-container-ms
    commit.image.appsody.dev/date: Thu Jun 25 15:49:46 2020 -0500
    commit.image.appsody.dev/message: Removed outdated mkdocs.yaml (#53)
    commit.stack.appsody.dev/author: Harish Yayi <yharish991@gmail.com>
    commit.stack.appsody.dev/committer: GitHub <noreply@github.com>
    commit.stack.appsody.dev/contextDir: /incubator/java-spring-boot2
    commit.stack.appsody.dev/date: Thu Jun 4 12:03:56 2020 +0100
    commit.stack.appsody.dev/message: 'java-springboot2: define APPSODY_DEBUG_PORT
      (#819)'
    image.opencontainers.org/created: "2020-07-10T12:43:54+02:00"
    image.opencontainers.org/documentation: https://github.com/jesusmah/refarch-kc-container-ms
    image.opencontainers.org/revision: 71c8facd4ff8a76b37a003f46edc33a51fca592b-modified
    image.opencontainers.org/source: https://github.com/jesusmah/refarch-kc-container-ms/tree/master
    image.opencontainers.org/url: https://github.com/jesusmah/refarch-kc-container-ms
    stack.appsody.dev/authors: Erin Schnabel <ebullient>, Ozzy Osborne <bardweller>,
      Richard Trotter <richard-trotter>, Harish Yayi <yharish991>
    stack.appsody.dev/configured: docker.io/appsody/java-spring-boot2:0.3
    stack.appsody.dev/created: "2020-06-04T11:06:14Z"
    stack.appsody.dev/description: Spring Boot using OpenJ9 and Maven
    stack.appsody.dev/documentation: https://github.com/appsody/stacks/tree/master/incubator/java-spring-boot2/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 7417563d37f987bc803711298b29817519cc648d
    stack.appsody.dev/source: https://github.com/appsody/stacks/tree/master/incubator/java-spring-boot2/image
    stack.appsody.dev/tag: docker.io/appsody/java-spring-boot2:0.3.30
    stack.appsody.dev/title: Spring Boot®
    stack.appsody.dev/url: https://github.com/appsody/stacks/tree/master/incubator/java-spring-boot2
  creationTimestamp: null
  labels:
    app.appsody.dev/name: refarch-kc
    app.kubernetes.io/part-of: refarch-kc
    image.opencontainers.org/title: spring-container-ms
    stack.appsody.dev/id: java-spring-boot2
    stack.appsody.dev/version: 0.3.30
  name: spring-container-ms
spec:
  applicationImage: ibmcase/kcontainer-spring-container-ms:test
  createKnativeService: false
  env:
  - name: KAFKA_BROKERS
    valueFrom:
      configMapKeyRef:
        key: brokers
        name: kafka-brokers
  - name: KAFKA_APIKEY
    valueFrom:
      secretKeyRef:
        key: binding
        name: eventstreams-apikey
        optional: true
  - name: KCSOLUTION_CONTAINERS_TOPIC
    valueFrom:
      configMapKeyRef:
        key: containersTopic
        name: kafka-topics
  - name: KCSOLUTION_ORDERS_TOPIC
    valueFrom:
      configMapKeyRef:
        key: ordersTopic
        name: kafka-topics
  - name: KCSOLUTION_CONTAINER_ANOMALY_RETRY_TOPIC
    valueFrom:
      configMapKeyRef:
        key: containerAnomalyRetryTopic
        name: kafka-topics
  - name: KCSOLUTION_CONTAINER_ANOMALY_DEAD_TOPIC
    valueFrom:
      configMapKeyRef:
        key: containerAnomalyDeadTopic
        name: kafka-topics
  - name: POSTGRESQL_URL
    valueFrom:
      secretKeyRef:
        key: binding
        name: postgresql-url
  - name: POSTGRESQL_USER
    valueFrom:
      secretKeyRef:
        key: binding
        name: postgresql-user
  - name: POSTGRESQL_PWD
    valueFrom:
      secretKeyRef:
        key: binding
        name: postgresql-pwd
  - name: ANOMALY_THRESHOLD
    valueFrom:
      configMapKeyRef:
        key: anomalyThreshold
        name: bpm-anomaly
        optional: true
  - name: BPM_ANOMALY
    valueFrom:
      configMapKeyRef:
        key: url
        name: bpm-anomaly
        optional: true
  - name: BPM_ANOMALY_LOGIN
    valueFrom:
      configMapKeyRef:
        key: login
        name: bpm-anomaly
        optional: true
  - name: BPM_EXPIRATION
    valueFrom:
      configMapKeyRef:
        key: expiration
        name: bpm-anomaly
        optional: true
  - name: BPM_ANOMALY_USER
    valueFrom:
      secretKeyRef:
        key: user
        name: bpm-anomaly
        optional: true
  - name: BPM_ANOMALY_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: bpm-anomaly
        optional: true
  expose: true
  livenessProbe:
    failureThreshold: 20
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
  monitoring:
    endpoints:
    - path: /actuator/prometheus
    labels:
      k8s-app: spring-container-ms
  readinessProbe:
    failureThreshold: 20
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: java-spring-boot2
  version: 1.0.0
status: {}
