site_name: Reefer Container Management Service
repo_url: https://github.com/ibm-cloud-architecture/refarch-kc-container-ms
nav:
  - Introduction: index.md
  - Analysis and design considerations: ES2DDD2MS.md
  - Springboot - Kafka and PostgreSQL Implementation: springboot/README.md
  - Deployments:
    - Pre-requisites: deployment.md
    - Run spring boot app locally: springboot/README.md
    - Continuous delivery: cicd.md
  - Reefer Container Predictive Maintenance:  https://ibm-cloud-architecture.github.io/refarch-reefer-ml/ 
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences