#!/bin/bash
p=$(pwd)
if [[ $p = */scripts ]]; then
 cd ..
fi


if [[ $# -ne 5 ]];then
   echo "Usage: deployhelm env repository tag namespace brokers"
   echo "example: deployhelm MINIKUBE ibmcase/kcontainer-spring-container-ms latest greencompute kafkabitmani:9092"
   echo "other example:  deployhelm IBMCLOUD us.icr.io/ibmcaseeda/kcontainer-spring-container-ms latest greencompute  kafka03-prod02.messagehub.services.us-south.bluemix.net:9093,kafka01-prod02.messagehub.services.us-south.bluemix.net:9093,kafka02-prod02.messagehub.services.us-south.bluemix.net:9093,kafka04-prod02.messagehub.services.us-south.bluemix.net:9093,kafka05-prod02.messagehub.services.us-south.bluemix.net:9093"
   exit
fi

kcenv=$1
repo=$2
kctag=$3
ns=$4
brokers=$5

msname=$(echo $repo |  cut -f2 -d'/' | cut -f2 -d'-')
rname=$(echo $repo |  cut -f2 -d'/')
pullPolicy="Never"

if [[ $kcenv != "MINIKUBE" ]]
then
  pullPolicy=Always
fi

echo "Deploy helm chart on $kcenv for $msname project to $ns with release named: $rname"

verifyPod(){
  kubectl logs $1 -n $ns
}

echo "############################"
oq=$(helm list | grep $rname | awk '{print $1}')
if [[ -z "$oq" ]]
then
  echo "$rname release not deployed... which is expected so deploy it"
  echo "helm install chart/$msname/ --name $rname --set image.repository=$repo \
    --set image.tag=$kctag --set image.pullSecret= --set image.pullPolicy=$pullPolicy \
    --set eventstreams.brokers=$brokers --set eventstreams.env=$kcenv --namespace $ns"

  helm install chart/$msname/ --name $rname --set image.repository=$repo \
    --set image.tag=$kctag --set image.pullSecret= --set image.pullPolicy=$pullPolicy \
    --set eventstreams.brokers=$brokers --set eventstreams.env=$kcenv --namespace $ns
  sleep 4
else
    echo "$rname release deployed, here is the pod logs"
    helm upgrade $rname $msname/ --set eventstreams.brokers=$brokers --set eventstreams.env=$kcenv
    helm history $msname
fi

podId=$(kubectl get pods -n $ns | grep $msname | awk '{print $1}')
verifyPod $podId
