# Build stage - could use maven or our image
FROM maven:3.3-jdk-8 as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# this is to reuse local .m2. if not all the dependencies will be always downloaded
#  it can be removed
VOLUME ${HOME}/.m2:/root/.m2
ADD . /usr/src/app
RUN bash -c "mvn clean install -DskipITs -Duser.home=/var/maven"

FROM openjdk:8u181-jdk as runner
ENV APP_HOME=/app
COPY --from=builder /usr/src/app/target/SpringContainerMS-1.0-SNAPSHOT.jar $APP_HOME/app.jar
LABEL maintainer="IBM Java Engineering at IBM Cloud"

# Install Extra Packages
RUN apt-get update \
 && apt-get install -y jq bash bc ca-certificates curl vim \
 && update-ca-certificates \
 && mkdir -p $APP_HOME/scripts

WORKDIR $APP_HOME

COPY scripts/startup.sh startup.sh
COPY scripts/add_certificates.sh scripts/

EXPOSE 8080:8080
ENTRYPOINT ["./startup.sh"]

